/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProducerService } from "../producer.service";
import { ProducerCreateInput } from "./ProducerCreateInput";
import { Producer } from "./Producer";
import { ProducerFindManyArgs } from "./ProducerFindManyArgs";
import { ProducerWhereUniqueInput } from "./ProducerWhereUniqueInput";
import { ProducerUpdateInput } from "./ProducerUpdateInput";

export class ProducerControllerBase {
  constructor(protected readonly service: ProducerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Producer })
  async createProducer(
    @common.Body() data: ProducerCreateInput
  ): Promise<Producer> {
    return await this.service.createProducer({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Producer] })
  @ApiNestedQuery(ProducerFindManyArgs)
  async producers(@common.Req() request: Request): Promise<Producer[]> {
    const args = plainToClass(ProducerFindManyArgs, request.query);
    return this.service.producers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Producer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async producer(
    @common.Param() params: ProducerWhereUniqueInput
  ): Promise<Producer | null> {
    const result = await this.service.producer({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Producer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProducer(
    @common.Param() params: ProducerWhereUniqueInput,
    @common.Body() data: ProducerUpdateInput
  ): Promise<Producer | null> {
    try {
      return await this.service.updateProducer({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Producer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProducer(
    @common.Param() params: ProducerWhereUniqueInput
  ): Promise<Producer | null> {
    try {
      return await this.service.deleteProducer({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
