/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Consumer as PrismaConsumer } from "@prisma/client";

export class ConsumerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ConsumerCountArgs, "select">): Promise<number> {
    return this.prisma.consumer.count(args);
  }

  async consumers(
    args: Prisma.ConsumerFindManyArgs
  ): Promise<PrismaConsumer[]> {
    return this.prisma.consumer.findMany(args);
  }
  async consumer(
    args: Prisma.ConsumerFindUniqueArgs
  ): Promise<PrismaConsumer | null> {
    return this.prisma.consumer.findUnique(args);
  }
  async createConsumer(
    args: Prisma.ConsumerCreateArgs
  ): Promise<PrismaConsumer> {
    return this.prisma.consumer.create(args);
  }
  async updateConsumer(
    args: Prisma.ConsumerUpdateArgs
  ): Promise<PrismaConsumer> {
    return this.prisma.consumer.update(args);
  }
  async deleteConsumer(
    args: Prisma.ConsumerDeleteArgs
  ): Promise<PrismaConsumer> {
    return this.prisma.consumer.delete(args);
  }
}
